/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bancoDigitalJava;

public class App {
    public static void main(String[] args) {
 
        Cliente Aldernei = new Cliente();
        Aldernei.setNome("Aldernei");
        
        ContaCorrente cc = new ContaCorrente(Aldernei);
        cc.depositar(100);
        
        ContaPoupanca poupanca = new ContaPoupanca(Aldernei);
        cc.transferir(100, poupanca);
        
        cc.imprimirExtrato();
        poupanca.imprimirExtrato();
    }
}
